name: scooter_rider_brasil
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.16.1
  provider: ^4.3.2+2
  font_awesome_flutter: ^8.11.0
  http: ^0.12.2
  direct_select: ^1.1.0
  # firebase_core: "^0.7.0"
  # firebase_auth: "^0.20.1"
  cloud_firestore: "^0.13.7"
  firebase_auth: "0.16.1"
  dropdown_search: ^0.5.0
  image_picker: ^0.6.7+4 # é necessário fazer algumas configurações para IOS
  firebase_storage: 3.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_srb.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/vs.png
   - assets/nmax.jpg
   - assets/pcx.jpg
   - assets/vs2.png
   - assets/nmax2.jpg
   - assets/pcx2.jpg
   - assets/image/logo_colorida.png
   - assets/image/like.png
   - assets/image/dica.png
   - assets/image/noticia.png
   - assets/image/inscricao.png
   - assets/image/review.png
   - assets/image/fimFeed.png
   - assets/logo_srb.png
   - assets/logo_srb2.png
   - assets/logo_srb3.png
   - assets/image/background.jpg
   - assets/image/semAvatar.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Azonix
      fonts:
        - asset: assets/fonts/Azonix.otf
    - family: Bookman
      fonts:
        - asset: assets/fonts/BOOKOS.TTF
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
